=== JOSM/josm-plugins/tageditor/test/osm-tag-definition-list.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/osm-tag-definition-list" xmlns:tns="http://www.example.org/osm-tag-definition-list" elementFormDefault="qualified">

 	<simpleType name = "OsmTagType">
    	<restriction base = "string">
      	<enumeration value = "string"/>
      	<enumeration value = "boolean"/>
    	</restriction>
 	 </simpleType>


    <complexType name="OsmTagDefinitionList">
    	<sequence>
    		<element name="osm-tag-definition" type="tns:OsmTagDefinition" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    	<attribute name="version" type="string"></attribute>
    </complexType>
    

    <complexType name="OsmTagDefinition">
    	<sequence>
    		<element ref="tns:displayName" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>

    		<element ref="tns:description" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>
    		<element name="label" type="tns:OsmLabelDefinition" minOccurs="0" 
    		maxOccurs="unbounded"></element>
    	</sequence>
    	<attribute name="key" type="string" use="required"></attribute>
    	<attribute name="iconName" type="string" use="optional"></attribute>
    	<attribute name="applicableForNode" type="boolean"
    		use="optional" default="true">
    	</attribute>
    	<attribute name="applicableForWay" type="boolean" use="optional"
    		default="true">
    	</attribute>
    	<attribute name="applicableForArea" type="boolean"
    		use="optional" default="true">
    	</attribute>
    	<attribute name="applicableForRelation" type="boolean"
    		use="optional" default="true">
    	</attribute>
    	<attribute name="type" type="tns:OsmTagType" use="optional"
    		default="string">
    	</attribute>
    </complexType>

    <complexType name="OsmLabelDefinition">
    	<sequence>
    		<element name="value" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element ref="tns:displayName" minOccurs="0" maxOccurs="unbounded"></element>
    		<element ref="tns:description" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    	<attribute name="iconName" type="string" use="optional"></attribute>
    	<attribute name="applicableForNode" type="boolean"
    		use="optional" default="true">
    	</attribute>
    	<attribute name="applicableForWay" type="boolean" use="optional"
    		default="true">
    	</attribute>
    	<attribute name="applicableForArea" type="boolean"
    		use="optional" default="true">
    	</attribute>
    	<attribute name="applicableForRelation" type="boolean"
    		use="optional" default="true">
    	</attribute>
    </complexType>



    <complexType name="OsmLocalizedString">
    	<simpleContent>
    	 	<extension base="string">
		    	<attribute name="locale" type="string" use="optional" default="en"></attribute>
    	 	</extension>
    	</simpleContent>
    </complexType>

 

    <element  name="displayName" type="tns:OsmLocalizedString"></element>
    
    <element  name="description" type="tns:OsmLocalizedString"></element>
    
    <element  name="osm-tag-definition-list" type="tns:OsmTagDefinitionList"></element>
</schema>

=== JOSM/josm-plugins/tageditor/test/osm-tag-definition-list.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:osm-tag-definition-list xmlns:tns="http://www.example.org/osm-tag-definition-list" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/osm-tag-definition-list osm-tag-definition-list.xsd " version="1.0">

<!-- ************************************************************************   -->
<!-- Highway: sample for a tag with one defined label and localized strings     -->
<!-- for two locales                                                            -->
<!-- ************************************************************************   -->
<tns:osm-tag-definition key="highway" iconName="highway.png">
	<tns:displayName locale="en">Highway</tns:displayName>
	<tns:displayName locale="de">Wege</tns:displayName>
	<tns:description locale="en">The highway tag is the primary tag used for highways. It is often the only tag. There are conventions for its use in particular countries.</tns:description>
	<tns:description locale="de">Der highway-Tag ist die hauptsächlich genutzte Art und Weise um Straßen zu kennzeichnen</tns:description>
		
	<tns:label>
	 	<tns:value>motorway</tns:value>
	 	<tns:displayName locale="en">Motorway</tns:displayName>
	 	<tns:displayName locale="de">Autobahn</tns:displayName>
	 	<tns:description locale="en">A restricted access major divided highway, normally with 2 or more running lanes plus emergency hard shoulder. Equivalent to the Freeway, Autobahn, etc.. </tns:description>
	 	<tns:description locale="de">Straße mit baulich getrennten Fahrtrichtungen (i. A. Grünstreifen) und besonderen Nutzungsbeschränkungen. Typischerweise zwei Fahrspuren je Fahrtrichtung oder mehr und ein Standstreifen.</tns:description>	 	
	</tns:label>
	
</tns:osm-tag-definition>

<!-- ************************************************************************   -->
<!-- building: sample for a tag of type boolean                                 -->
<!-- ************************************************************************   -->
<tns:osm-tag-definition key="building" type="boolean">
</tns:osm-tag-definition>


</tns:osm-tag-definition-list>
