=== JOSM/josm-plugins/routes/src/org/openstreetmap/josm/plugins/routes/xml/routes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema 
xmlns="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://www.example.org/routes" 
xmlns:tns="http://www.example.org/routes" 
elementFormDefault="qualified"
xmlns:jxb="http://java.sun.com/xml/ns/jaxb" 
jxb:version="1.0"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://java.sun.com/xml/ns/jaxb http://java.sun.com/xml/ns/jaxb/bindingschema_1_0.xsd">

<annotation>
	<appinfo>
		<jxb:schemaBindings>	
			<jxb:nameXmlTransform>
				<jxb:typeName prefix="RoutesXML"/>
			</jxb:nameXmlTransform>
		</jxb:schemaBindings>
	</appinfo>
</annotation>

<element name="routes">
	<complexType>
		<sequence>
			<element name="layer" type="tns:layer" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
	</complexType>
</element>

<complexType name="layer">
	<sequence>
		<element name="route" type="tns:route" minOccurs="0" maxOccurs="unbounded"/>
	</sequence>
	<attribute name="name" type="string"/>
</complexType>

<complexType name="route">
	<sequence>
		<element name="pattern" type="string"/>		
	</sequence>
	<attribute name="color" type="string"/>
</complexType>

</schema>

=== JOSM/josm-plugins/routes/src/org/openstreetmap/josm/plugins/routes/xml/routes.xml
<?xml version="1.0" encoding="UTF-8"?>
<routes xmlns="http://www.example.org/routes" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/routes routes.xsd ">
<!-- pattern is the same pattern as used in SearchAction -->
	<layer name="Czech hiking trails">
		<route color="#FF0000">
			<pattern>
			((type:relation | type:way) kct_red=*) | (color=red type=route route=hiking network=cz:kct)
			</pattern>
		</route>
		<route color="#FFFF00">
			<pattern>
			((type:relation | type:way) kct_yellow=*) | (color=yellow type=route route=hiking network=cz:kct)
			</pattern>			
		</route>
		<route color="#0000FF">
			<pattern>
			((type:relation | type:way) kct_blue=*) | (color=blue type=route route=hiking network=cz:kct)
			</pattern>
		</route>
		<route color="#00FF00">
			<pattern>
			((type:relation | type:way) kct_green=*) | (color=green type=route route=hiking network=cz:kct)
			</pattern>		
		</route>
	</layer>
	<layer name="Cycle routes">
		<route color="#FF00FF">
			<pattern>
			(type:way (ncn=* | (lcn=* | rcn=* ))) | (type:relation type=route route=bicycle)
			</pattern>
		</route>
	</layer>
</routes>
