=== JOSM/josm-plugins/tageditor/src/org/openstreetmap/josm/plugins/tageditor/tagspec/osm-tag-definitions.dtd
<!ELEMENT osm-tag-definitions (tag*)>
<!ATTLIST osm-tag-definitions
     version CDATA #FIXED '0.9'
     xmlns:xs CDATA #FIXED 'http://www.w3.org/2001/XMLSchema-datatypes'
>
<!ELEMENT tag (label*) >
<!ATTLIST tag
     key CDATA #REQUIRED
     type CDATA #REQUIRED
     for-way (yes|no) 'no' 
     for-node (yes|no) 'no' 
     for-relation (yes|no) 'no'
>
<!ELEMENT label EMPTY>
<!ATTLIST label
     value CDATA #REQUIRED 
     for-way (yes|no) 'no' 
     for-node (yes|no) 'no' 
     for-relation (yes|no) 'no'
>

=== JOSM/josm-plugins/tageditor/resources/osm-tag-definitions.xml
<?xml version="1.0"?>
<!DOCTYPE osm-tag-definitions SYSTEM "osm-tag-definitions.dtd">
<osm-tag-definitions version="0.9"
	xmlns:xs="http://www.w3.org/2001/XMLSchema-datatypes">

		
	<tag key="highway" type="xs:string" for-way="yes" for-node="yes">
		<label value="motorway" for-way="yes"/>
		<label value="motorway_link" for-way="yes"/>
		<label value="trunk" for-way="yes"/>
		<label value="trunk_link" for-way="yes"/>
		<label value="primary" for-way="yes"/>
		<label value="primary_link" for-way="yes"/>
		<label value="secondary" for-way="yes"/>
		<label value="tertiary" for-way="yes"/>
		<label value="unclassified" for-way="yes"/>
		<label value="road" for-way="yes"/>
		<label value="residential" for-way="yes"/>
		<label value="living_street" for-way="yes"/>
		<label value="service" for-way="yes"/>
		<label value="track" for-way="yes"/>
		<label value="pedestrian" for-way="yes" for-relation="yes"/>
		<label value="services" for-way="yes"/>
		<label value="bus_guideway" for-way="yes"/>	
		<label value="path" for-way="yes"/>
		<label value="cycleway" for-way="yes"/>
		<label value="footway" for-way="yes"/>
		<label value="bridleway" for-way="yes"/>
		<label value="byway" for-way="yes"/>
		<label value="steps" for-way="yes"/>
		<label value="mini_roundabout" for-node="yes"/>
		<label value="stop" for-node="yes"/>
		<label value="traffic_signals" for-node="yes"/>
		<label value="incline" for-node="yes"/>
		<label value="incline_steep" for-node="yes"/>
		<label value="ford" for-node="yes"/>
		<label value="bus_stop" for-node="yes"/>
		<label value="turning_circle" for-node="yes"/>
		<label value="construction" for-way="yes"/>
		<label value="emergency_access_point" for-node="yes"/>
		<label value="motorway_junction" for-node="yes"/>
	</tag>	
	
	
	
		
	<tag key="junction" type="xs:string" for-way="yes" for-node="yes" >
		<label value="roundabout" for-way="yes"/>		
	</tag>

	<tag key="traffic_calming" type="xs:string" for-way="yes" for-node="yes" >
		<label value="yes" for-way="yes" for-node="yes"/>
		<label value="bump" for-way="yes" for-node="yes"/>
		<label value="chicane" for-way="yes" for-node="yes"/>
		<label value="cushion" for-way="yes" for-node="yes"/>
		<label value="hump" for-way="yes" for-node="yes"/>
		<label value="rumble_strip" for-way="yes" for-node="yes"/>
		<label value="table" for-way="yes" for-node="yes"/>
		<label value="choker" for-way="yes" for-node="yes"/>
	</tag>

	<tag key="service" type="xs:string" for-way="yes">
		<label value="parking_aisle" for-way="yes"/>
		<label value="driveway" for-way="yes"/>
		<label value="alley" for-way="yes"/>
	</tag>
	
	<tag key="smoothness" type="xs:string" for-way="yes">
		<label value="excellent" for-way="yes"/>
		<label value="good" for-way="yes"/>
		<label value="intermediate" for-way="yes"/>
		<label value="bad" for-way="yes"/>
		<label value="very_bad" for-way="yes"/>
		<label value="horrible" for-way="yes"/>
		<label value="very_horrible" for-way="yes"/>
		<label value="impassable" for-way="yes"/>
	</tag>
	
	<tag key="barrier" type="xs:string" for-way="yes" for-node="yes">
		<label value="hedge" for-way="yes"/>
		<label value="fence" for-way="yes"/>
		<label value="wall" for-way="yes"/>
		<label value="ditch" for-way="yes"/>
		<label value="retaining_wall" for-way="yes"/>
		<label value="city_wall" for-way="yes"/>
		
		<label value="entrance" for-node="yes"/>
		<label value="bollard" for-node="yes"/>
		<label value="gate" for-node="yes"/>
		<label value="stile" for-node="yes"/>
		<label value="cattle_grid" for-node="yes"/>
		<label value="cycle_barrier" for-node="yes"/>
		<label value="toll_booth" for-node="yes"/>
		<label value="sally_port" for-node="yes"/>
	</tag>
	
	
	
	<tag key="cycleway" type="xs:string" for-way="yes">
		<label value="lane" for-way="yes"/>
		<label value="track" for-way="yes"/>
		<label value="opposite_lane" for-way="yes"/>
		<label value="opposite_track" for-way="yes"/>
		<label value="opposite" for-way="yes"/>
	</tag>
	
	<tag key="smoothness" type="xs:string" for-way="yes">
		<label value="excellent" for-way="yes"/>
		<label value="good" for-way="yes"/>
		<label value="intermediate" for-way="yes"/>
		<label value="bad" for-way="yes"/>
		<label value="very_bad" for-way="yes"/>
		<label value="horrible" for-way="yes"/>
		<label value="very_horrible" for-way="yes"/>
		<label value="impassable" for-way="yes"/>
	</tag>
	
	<tag key="tracktype" type="xs:string" for-way="yes">
		<label value="grade1" for-way="yes"/>
		<label value="grade2" for-way="yes"/>
		<label value="grade3" for-way="yes"/>
		<label value="grade4" for-way="yes"/>
		<label value="grade5" for-way="yes"/>
	</tag>

	<tag key="waterway" type="xs:string" for-way="yes">
		<label value="stream" for-way="yes"/>
		<label value="river" for-way="yes"/>
		<label value="riverbank" for-way="yes"/>
		<label value="canal" for-way="yes"/>		
		<label value="drain" for-way="yes"/>
		<label value="dock" for-way="yes" for-node="yes"/>
		<label value="lock_gate" for-node="yes"/>
		<label value="turning_point" for-node="yes"/>
		<label value="boatyard" for-node="yes"/>
		<label value="weir" for-way="yes" for-node="yes"/>
		<label value="dam" for-way="yes"/>
	</tag>
	
	<tag key="lock" type="xs:string" for-way="yes" for-node="yes">
		<label value="yes" for-way="yes"/>
		<label value="no" for-way="yes"/>
	</tag>

	<tag key="mooring" type="xs:string" for-way="yes">
		<label value="yes" for-way="yes"/>
		<label value="no" for-way="yes"/>
		<label value="private" for-way="yes"/>
	</tag>
	
	<tag key="railway" type="xs:string" for-way="yes" for-node="yes">
		<label value="rail" for-way="yes"/>
		<label value="tram" for-way="yes"/>
		<label value="light_rail" for-way="yes"/>
		<label value="subway" for-way="yes"/>
		<label value="preserved" for-way="yes"/>
		<label value="disused" for-way="yes"/>
		<label value="abandoned" for-way="yes"/>
		<label value="narrow_gauge" for-way="yes"/>
		<label value="monorail" for-way="yes"/>
		<label value="station" for-node="yes"/>
		<label value="halt" for-node="yes"/>
		<label value="tram_stop" for-node="yes"/>
		<label value="crossing" for-node="yes"/>
		<label value="level_crossing" for-node="yes"/>
		<label value="subway_entrance" for-node="yes"/>
		<label value="turntable" for-node="yes" for-way="yes"/>
		<label value="platform" for-way="yes"/>
	</tag>
	
	<tag key="electrified" type="xs:string" for-way="yes">
		<label value="contact_line" for-way="yes"/>
		<label value="rail" for-way="yes"/>
		<label value="yes" for-way="yes"/>
		<label value="no" for-way="yes"/>
	</tag>

	<tag key="frequency" type="xs:string" for-way="yes">
	</tag>

	<tag key="voltage" type="xs:string" for-way="yes">
	</tag>
	
	<tag key="service" type="xs:string" for-way="yes">
		<label value="yard" for-way="yes"/>
		<label value="siding" for-way="yes"/>
		<label value="spur" for-way="yes"/>
	</tag>
	
	
	<tag key="aeroway" type="xs:string" for-way="yes" for-node="yes">
		<label value="aerodrome" for-node="yes"/>
		<label value="terminal" for-node="yes"/>
		<label value="helipad" for-node="yes"/>
		<label value="runway" for-way="yes"/>
		<label value="taxiway" for-way="yes"/>
		<label value="apron" for-way="yes"/>
		<label value="gate" for-node="yes"/>
	</tag>
	
	<tag key="aerialway" type="xs:string" for-way="yes" for-node="yes">
		<label value="cable_car" for-way="yes"/>
		<label value="chair_lift" for-way="yes"/>
		<label value="drag_lift" for-way="yes"/>
		<label value="station" for-node="yes"/>		
	</tag>

	<tag key="power" type="xs:string" for-way="yes" for-node="yes">
		<label value="tower" for-node="yes"/>
		<label value="line" for-way="yes"/>
		<label value="station" for-node="yes" for-way="yes" /> <!--  area  -->
		<label value="sub_station" for-node="yes" for-way="yes"/> <!--  area  -->
		<label value="generator" for-node="yes" for-way="yes"/> <!--  area  -->
	</tag>
	
	<tag key="wires" type="xs:string" for-way="yes">
		<label value="single" for-way="yes"/>
		<label value="double" for-way="yes"/>
		<label value="tripple" for-way="yes"/>
		<label value="quad" for-way="yes"/>		
	</tag>	

	<tag key="cables" type="xs:string" for-way="yes">
	</tag>	

	<tag key="man_made" type="xs:string" for-way="yes" for-node="yes">
		<label value="beacon" for-node="yes"/>
		<label value="crane" for-node="yes"/>
		<label value="gasometer" for-node="yes"/>
		<label value="lighthouse" for-node="yes"/>		
		<label value="pier" for-way="yes"/> <!--  area  -->		
		<label value="pipeline" for-way="yes"/>		
		<label value="reservoir_covered" for-node="yes" for-way="yes"/>	<!--  area  -->			
		<label value="surveillance" for-node="yes" for-way="yes"/>	<!--  area  -->
		<label value="survey_point" for-node="yes" />	
		<label value="tower" for-node="yes" />
		<label value="wastewater_plant" for-node="yes" for-way="yes"/>	<!--  area  -->
		<label value="watermill" for-node="yes" for-way="yes"/>	<!--  area  -->
		<label value="water_tower" for-node="yes" />
		<label value="water_works" for-node="yes" />
		<label value="windmill" for-node="yes" />
		<label value="works" for-node="yes" />
	</tag>	
	
	<tag key="building" type="xs:string" for-way="yes" >
		<label value="yes" for-way="yes" /> <!--  area -->
	</tag>	

	<tag key="leisure" type="xs:string" for-way="yes" for-node="yes">
		<label value="sports_centre" for-way="yes" for-node="yes"/>
		<label value="golf_course" for-way="yes" for-node="yes"/>
		<label value="stadium" for-way="yes" for-node="yes"/>
		<label value="track" for-way="yes" for-node="yes"/>
		<label value="pitch" for-way="yes" for-node="yes"/>
		<label value="water_park" for-way="yes" for-node="yes"/>	
		<label value="marina" for-way="yes" for-node="yes"/>
		<label value="slipway" for-node="yes"/>
